name: chitchat
base: core22
version: '0.0.1a'
summary: Universal Terminal Messaging Client
description: |
  ChitChat is a terminal-based messaging client that supports multiple platforms.
  Currently supports WhatsApp and Slack, with more services coming soon!
  
  Features:
  - Clean TUI interface built with OpenTUI
  - Multi-service support (WhatsApp, Slack)
  - Media support (images, documents, audio)
  - QR code authentication for WhatsApp
  - Demo mode for testing
  
  Usage: chitchat [--demo]

license: ISC
website: https://github.com/Botolog/ChitChat
issues: https://github.com/Botolog/ChitChat/issues
source-code: https://github.com/Botolog/ChitChat

confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  chitchat:
    command: bin/chitchat
    plugs:
      - network
      - network-bind
      - home
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  bun:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      # Install Bun
      curl -fsSL https://bun.sh/install | bash
      cp -r $HOME/.bun $CRAFT_PART_INSTALL/
    stage:
      - .bun/bin/bun

  chitchat:
    plugin: nil
    source: .
    after: [bun]
    build-packages:
      - curl
      - git
    override-build: |
      # Set up Bun in PATH
      export PATH="$CRAFT_STAGE/.bun/bin:$PATH"
      
      # Install dependencies
      bun install --frozen-lockfile
      
      # Build the application
      bun build src/index.ts \
        --compile \
        --minify \
        --target=bun \
        --outfile $CRAFT_PART_INSTALL/bin/chitchat
      
      # Make executable
      chmod +x $CRAFT_PART_INSTALL/bin/chitchat
    stage:
      - bin/chitchat
