name: chitchat
base: core22
version: '0.0.1a'
summary: Universal Terminal Messaging Client
description: |
  ChitChat is a terminal-based messaging client that supports multiple platforms.
  Currently supports WhatsApp and Slack, with more services coming soon!
  
  Features:
  - Clean TUI interface built with OpenTUI
  - Multi-service support (WhatsApp, Slack)
  - Media support (images, documents, audio)
  - QR code authentication for WhatsApp
  - Demo mode for testing
  
  Usage: chitchat [--demo]

license: ISC
website: https://github.com/Botolog/ChitChat
issues: https://github.com/Botolog/ChitChat/issues
source-code: https://github.com/Botolog/ChitChat

confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  chitchat:
    command: bin/chitchat
    plugs:
      - network
      - network-bind
      - home
    environment:
      HOME: $SNAP_USER_COMMON
      TMPDIR: $SNAP_USER_COMMON/tmp

parts:
  bun:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      # Install Bun
      curl -fsSL https://bun.sh/install | bash
      cp -r $HOME/.bun $CRAFT_PART_INSTALL/
    stage:
      - .bun/bin/bun

  chitchat:
    plugin: nil
    source: .
    after: [bun]
    build-packages:
      - curl
      - git
    override-build: |
      # Set up Bun in PATH
      export PATH="$CRAFT_STAGE/.bun/bin:$PATH"
      
      # Install dependencies
      bun install --frozen-lockfile
      
      # Copy source files and node_modules to app directory
      mkdir -p $CRAFT_PART_INSTALL/app
      cp -r $CRAFT_PART_SRC/src $CRAFT_PART_INSTALL/app/
      cp -r $CRAFT_PART_SRC/node_modules $CRAFT_PART_INSTALL/app/
      cp $CRAFT_PART_SRC/package.json $CRAFT_PART_INSTALL/app/ || echo "Warning: package.json not copied"
      
      # Create wrapper script to run with Bun runtime
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/chitchat << 'EOF'
      #!/bin/bash
      cd "$SNAP/app"
      exec "$SNAP/.bun/bin/bun" run src/index.ts "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/chitchat
    stage:
      - app/
      - bin/chitchat
