name: chitchat
base: core22
version: '0.0.1a'
summary: Universal Terminal Messaging Client
description: |
  ChitChat is a terminal-based messaging client that supports multiple platforms.
  Currently supports WhatsApp and Slack, with more services coming soon!
  
  Features:
  - Clean TUI interface built with OpenTUI
  - Multi-service support (WhatsApp, Slack)
  - Media support (images, documents, audio)
  - QR code authentication for WhatsApp
  - Demo mode for testing
  
  Usage: chitchat [--demo]

license: ISC
website: https://github.com/Botolog/ChitChat
issues: https://github.com/Botolog/ChitChat/issues
source-code: https://github.com/Botolog/ChitChat

confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  chitchat:
    command: bin/chitchat
    plugs:
      - network
      - network-bind
      - home
      - browser-support
    environment:
      HOME: $SNAP_USER_COMMON
      TMPDIR: $SNAP_USER_COMMON/tmp
      CHITCHAT_DATA_DIR: $SNAP_USER_COMMON
      NODE_PATH: $SNAP/app/node_modules
      PUPPETEER_CACHE_DIR: $SNAP_USER_COMMON/.cache/puppeteer

parts:
  bun:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      # Install Bun
      curl -fsSL https://bun.sh/install | bash
      cp -r $HOME/.bun $CRAFT_PART_INSTALL/
    stage:
      - .bun/bin/bun

  chitchat:
    plugin: nil
    source: .
    after: [bun]
    build-packages:
      - curl
      - git
    stage-packages:
      - ca-certificates
      - fonts-liberation
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libgbm1
      - libglib2.0-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
    override-build: |
      # Set up Bun in PATH
      export PATH="$CRAFT_STAGE/.bun/bin:$PATH"
      
      # Install dependencies
      bun install --frozen-lockfile
      
      # Copy source files and node_modules to app directory
      mkdir -p $CRAFT_PART_INSTALL/app
      cp -r $CRAFT_PART_SRC/src $CRAFT_PART_INSTALL/app/
      cp -r $CRAFT_PART_SRC/node_modules $CRAFT_PART_INSTALL/app/
      cp $CRAFT_PART_SRC/package.json $CRAFT_PART_INSTALL/app/ || echo "Warning: package.json not copied"
      
      # Create wrapper script to run with Bun runtime
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/chitchat << 'EOF'
      #!/bin/bash
      # Ensure writable data directory exists
      mkdir -p "$SNAP_USER_COMMON"
      # Change to writable directory so process.cwd() points to writable location
      cd "$SNAP_USER_COMMON"
      # Run from snap app directory but with CWD in writable location
      exec "$SNAP/.bun/bin/bun" run "$SNAP/app/src/index.ts" "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/chitchat
    stage:
      - app/
      - bin/chitchat
